-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE echo_event (
  event_id SERIAL NOT NULL,
  event_type TEXT NOT NULL,
  event_agent_id INT DEFAULT NULL,
  event_agent_ip TEXT DEFAULT NULL,
  event_extra TEXT DEFAULT NULL,
  event_page_id INT DEFAULT NULL,
  event_deleted SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(event_id)
);

CREATE INDEX echo_event_type ON echo_event (event_type);

CREATE INDEX echo_event_page_id ON echo_event (event_page_id);


CREATE TABLE echo_notification (
  notification_event INT NOT NULL,
  notification_user INT NOT NULL,
  notification_timestamp TIMESTAMPTZ NOT NULL,
  notification_read_timestamp TIMESTAMPTZ DEFAULT NULL,
  notification_bundle_hash TEXT NOT NULL,
  PRIMARY KEY(
    notification_user, notification_event
  )
);

CREATE INDEX echo_user_timestamp ON echo_notification (
  notification_user, notification_timestamp
);

CREATE INDEX echo_notification_event ON echo_notification (notification_event);

CREATE INDEX echo_notification_user_read_timestamp ON echo_notification (
  notification_user, notification_read_timestamp
);


CREATE TABLE echo_email_batch (
  eeb_id SERIAL NOT NULL,
  eeb_user_id INT NOT NULL,
  eeb_event_priority SMALLINT DEFAULT 10 NOT NULL,
  eeb_event_id INT NOT NULL,
  eeb_event_hash TEXT NOT NULL,
  PRIMARY KEY(eeb_id)
);

CREATE UNIQUE INDEX echo_email_batch_user_event ON echo_email_batch (eeb_user_id, eeb_event_id);

CREATE INDEX echo_email_batch_user_hash_priority ON echo_email_batch (
  eeb_user_id, eeb_event_hash, eeb_event_priority
);


CREATE TABLE echo_target_page (
  etp_id SERIAL NOT NULL,
  etp_page INT DEFAULT 0 NOT NULL,
  etp_event INT DEFAULT 0 NOT NULL,
  PRIMARY KEY(etp_id)
);

CREATE INDEX echo_target_page_event ON echo_target_page (etp_event);

CREATE INDEX echo_target_page_page_event ON echo_target_page (etp_page, etp_event);
