-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables-push.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE echo_push_provider (
  epp_id SMALLSERIAL NOT NULL,
  epp_name TEXT NOT NULL,
  PRIMARY KEY(epp_id)
);


CREATE TABLE echo_push_subscription (
  eps_id SERIAL NOT NULL,
  eps_user INT NOT NULL,
  eps_token TEXT NOT NULL,
  eps_token_sha256 CHAR(64) NOT NULL,
  eps_provider SMALLINT NOT NULL,
  eps_updated TIMESTAMPTZ NOT NULL,
  eps_data TEXT DEFAULT NULL,
  eps_topic SMALLINT DEFAULT NULL,
  PRIMARY KEY(eps_id)
);

CREATE UNIQUE INDEX eps_token_sha256 ON echo_push_subscription (eps_token_sha256);

CREATE INDEX eps_provider ON echo_push_subscription (eps_provider);

CREATE INDEX eps_topic ON echo_push_subscription (eps_topic);

CREATE INDEX eps_user ON echo_push_subscription (eps_user);

CREATE INDEX eps_token ON echo_push_subscription (eps_token);


CREATE TABLE echo_push_topic (
  ept_id SMALLSERIAL NOT NULL,
  ept_text TEXT NOT NULL,
  PRIMARY KEY(ept_id)
);
