-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/echo_event (
  event_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  event_type VARBINARY(64) NOT NULL,
  event_agent_id INT UNSIGNED DEFAULT NULL,
  event_agent_ip VARBINARY(39) DEFAULT NULL,
  event_extra BLOB DEFAULT NULL,
  event_page_id INT UNSIGNED DEFAULT NULL,
  event_deleted TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  INDEX echo_event_type (event_type),
  INDEX echo_event_page_id (event_page_id),
  PRIMARY KEY(event_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/echo_notification (
  notification_event INT UNSIGNED NOT NULL,
  notification_user INT UNSIGNED NOT NULL,
  notification_timestamp BINARY(14) NOT NULL,
  notification_read_timestamp BINARY(14) DEFAULT NULL,
  notification_bundle_hash VARBINARY(32) NOT NULL,
  INDEX echo_user_timestamp (
    notification_user, notification_timestamp
  ),
  INDEX echo_notification_event (notification_event),
  INDEX echo_notification_user_read_timestamp (
    notification_user, notification_read_timestamp
  ),
  PRIMARY KEY(
    notification_user, notification_event
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/echo_email_batch (
  eeb_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  eeb_user_id INT UNSIGNED NOT NULL,
  eeb_event_priority TINYINT UNSIGNED DEFAULT 10 NOT NULL,
  eeb_event_id INT UNSIGNED NOT NULL,
  eeb_event_hash VARBINARY(32) NOT NULL,
  UNIQUE INDEX echo_email_batch_user_event (eeb_user_id, eeb_event_id),
  INDEX echo_email_batch_user_hash_priority (
    eeb_user_id, eeb_event_hash, eeb_event_priority
  ),
  PRIMARY KEY(eeb_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/echo_target_page (
  etp_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  etp_page INT UNSIGNED DEFAULT 0 NOT NULL,
  etp_event INT UNSIGNED DEFAULT 0 NOT NULL,
  INDEX echo_target_page_event (etp_event),
  INDEX echo_target_page_page_event (etp_page, etp_event),
  PRIMARY KEY(etp_id)
) /*$wgDBTableOptions*/;
