-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables-push.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/echo_push_provider (
  epp_id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
  epp_name TINYBLOB NOT NULL,
  PRIMARY KEY(epp_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/echo_push_subscription (
  eps_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  eps_user INT UNSIGNED NOT NULL,
  eps_token BLOB NOT NULL,
  eps_token_sha256 CHAR(64) NOT NULL,
  eps_provider TINYINT UNSIGNED NOT NULL,
  eps_updated TIMESTAMP NOT NULL,
  eps_data BLOB DEFAULT NULL,
  eps_topic TINYINT UNSIGNED DEFAULT NULL,
  UNIQUE INDEX eps_token_sha256 (eps_token_sha256),
  INDEX eps_provider (eps_provider),
  INDEX eps_topic (eps_topic),
  INDEX eps_user (eps_user),
  INDEX eps_token (
    eps_token(10)
  ),
  PRIMARY KEY(eps_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/echo_push_topic (
  ept_id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ept_text TINYBLOB NOT NULL,
  PRIMARY KEY(ept_id)
) /*$wgDBTableOptions*/;
